CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    org_name VARCHAR(50) UNIQUE                            NOT NULL,
    email VARCHAR(50)                                      NOT NULL,
    role VARCHAR(20)                                       NOT NULL
    );

CREATE TABLE IF NOT EXISTS participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    fio VARCHAR(50) UNIQUE                                 NOT NULL,
    age INTEGER                                            NOT NULL,
    email VARCHAR(50)                                      NOT NULL,
    pcrTest VARCHAR(20)                                    NOT NULL,
    role VARCHAR(20)                                       NOT NULL
    );

CREATE TABLE IF NOT EXISTS principal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50) UNIQUE                                NOT NULL,
    inn BIGINT                                             NOT NULL
    );

CREATE TABLE IF NOT EXISTS contracts (
    number BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    terms VARCHAR(1000)                                    NOT NULL,
    status VARCHAR(50)                                     NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE                 NOT NULL,
    signing_on TIMESTAMP WITHOUT TIME ZONE,
    admin_id BIGINT REFERENCES admins (id) ON DELETE CASCADE,
    principal_id BIGINT REFERENCES principal (id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    eventName VARCHAR(50)                                  NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE                 NOT NULL,
    eventDate TIMESTAMP WITHOUT TIME ZONE                  NOT NULL,
    rate BIGINT                                            NOT NULL,
    request_moderation BOOLEAN DEFAULT TRUE,
    admin_id BIGINT REFERENCES admins (id) ON DELETE CASCADE,
    status VARCHAR(50)                                     NOT NULL
    );

CREATE TABLE IF NOT EXISTS requests (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    requester_id BIGINT REFERENCES participants(id) ON DELETE CASCADE,
    status VARCHAR(50),
    created TIMESTAMP WITHOUT TIME ZONE                       NOT NULL
    );